# Generated by Django 4.0.3 on 2022-03-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=8)),
                ('username', models.CharField(max_length=50)),
                ('current_education', models.CharField(max_length=8)),
                ('stream', models.CharField(max_length=16)),
                ('educational_institution', models.CharField(max_length=100)),
                ('target_exam', models.CharField(max_length=8)),
                ('pincode', models.IntegerField(max_length=6)),
                ('city', models.CharField(max_length=16)),
                ('address', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=16)),
                ('phone', models.IntegerField(max_length=13)),
                ('email', models.CharField(max_length=50)),
                ('userid', models.CharField(max_length=8)),
                ('otp', models.IntegerField(max_length=6)),
                ('password_hash', models.CharField(max_length=100)),
                ('hash', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField()),
                ('mobile_verify', models.CharField(max_length=8)),
                ('email_verify', models.CharField(max_length=8)),
                ('token', models.CharField(max_length=100)),
                ('jee_subid', models.CharField(max_length=16)),
                ('neet_subid', models.CharField(max_length=16)),
                ('board_subid', models.CharField(max_length=16)),
                ('upsc_subid', models.CharField(max_length=16)),
                ('cat_subid', models.CharField(max_length=16)),
                ('progm_subid', models.CharField(max_length=16)),
                ('psu_subid', models.CharField(max_length=16)),
            ],
        ),
    ]
