# Generated by Django 4.0.3 on 2022-03-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jee',
            name='thumbnail',
            field=models.ImageField(upload_to='media'),
        ),
    ]
