# Generated by Django 4.0.3 on 2022-03-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_jee_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_image_upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
                ('image', models.ImageField(upload_to='media')),
            ],
        ),
    ]
