# Generated by Django 4.0.3 on 2022-03-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_test_image_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_image_upload',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
