# Generated by Django 4.0.3 on 2022-03-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_test_image_upload_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_image_upload',
            name='image',
            field=models.CharField(max_length=64),
        ),
    ]
