# Generated by Django 4.0.3 on 2022-04-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_test_image_upload_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='jee',
            name='sub',
            field=models.CharField(default='MATH', max_length=16),
            preserve_default=False,
        ),
    ]
