# Generated by Django 4.0.3 on 2022-04-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_jee_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='neet',
            name='sub',
            field=models.CharField(default='BIOLOGY', max_length=16),
            preserve_default=False,
        ),
    ]
