# Generated by Django 4.0.3 on 2022-04-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_neet_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boards',
            name='video_url',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cat',
            name='video_url',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jee',
            name='video_url',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='neet',
            name='video_url',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='other',
            name='video_url',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='progm',
            name='video_url',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='psu',
            name='video_url',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='upsc',
            name='video_url',
            field=models.CharField(max_length=100),
        ),
    ]
