# Generated by Django 4.0.3 on 2022-04-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_boards_video_url_alter_cat_video_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=8)),
                ('userid', models.CharField(max_length=8)),
                ('username', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField()),
            ],
        ),
    ]
