# Generated by Django 4.0.3 on 2022-04-25 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='created_on',
        ),
    ]
